#!/usr/bin/bash

SECONDS=0
for i in $(seq 200); do
        cat ../c.txt | LD_PRELOAD=../lib/lib440lib.so ../tools/440write output.txt > out_${i}.txt &
done
wait
duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
