#!/usr/bin/bash
SECONDS=0
for i in $(seq 200); do
        LD_PRELOAD=../lib/lib440lib.so ../tools/440cat 1mb.txt > out_${i}.txt &
        sleep 0.5
done
wait
duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
