#!/usr/bin/bash
SECONDS=0
for i in $(seq 100); do
	LD_PRELOAD=../lib/lib440lib.so ../tools/440cat sherlock.txt > out_${i}.txt &
done
wait
duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
